# Generated by Django 3.1.1 on 2020-09-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200908_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pars_url',
            field=models.TextField(blank=True, verbose_name='Url для парсинга'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='slug'),
        ),
    ]
