# Generated by Django 3.1.1 on 2020-09-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200909_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pars_url',
        ),
        migrations.AddField(
            model_name='category',
            name='pars_url_sports',
            field=models.TextField(blank=True, verbose_name='Url для парсинга SPORTS.RU'),
        ),
        migrations.AddField(
            model_name='category',
            name='pars_url_tut',
            field=models.TextField(blank=True, verbose_name='Url для парсинга TUT.BY'),
        ),
    ]
